/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg1bookcloud;

import java.awt.Color;
import static pkg1bookcloud.c1_Login.next;
import static pkg1bookcloud.c1_Login.forgotpassword;
import static pkg1bookcloud.c2_Signup.next;


/**
 *
 * @author nooralsharif
 */
public class b_Startpage extends javax.swing.JFrame {

    /**
     * Creates new form b_Startpage
     */
    public b_Startpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        copyright = new javax.swing.JLabel();
        signupclicked = new javax.swing.JLabel();
        loginclicked = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        Signup = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(375, 830));
        setMinimumSize(new java.awt.Dimension(375, 830));
        setPreferredSize(new java.awt.Dimension(375, 812));
        getContentPane().setLayout(null);

        copyright.setBackground(new java.awt.Color(255, 255, 255));
        copyright.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        copyright.setForeground(new java.awt.Color(51, 51, 51));
        copyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copyright.setText("Copyright © 2020 Book Cloud");
        copyright.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(copyright);
        copyright.setBounds(50, 740, 280, 50);

        signupclicked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/New 2 Start page – 1.png"))); // NOI18N
        getContentPane().add(signupclicked);
        signupclicked.setBounds(47, 456, 290, 80);
        loginclicked.setVisible(false);
        signupclicked.setVisible(false);

        loginclicked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/New 2 Start page – 2.png"))); // NOI18N
        getContentPane().add(loginclicked);
        loginclicked.setBounds(47, 350, 290, 80);
        loginclicked.setVisible(false);

        Login.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Login.setForeground(new java.awt.Color(123, 92, 170));
        Login.setToolTipText("");
        Login.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Login.setBorderPainted(false);
        Login.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Login.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginMouseEntered(evt);
            }
        });
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Login);
        Login.setBounds(45, 350, 290, 80);
        Login.setOpaque(false);
        Login.setContentAreaFilled(false);
        Login.setBorderPainted(false);

        Signup.setBackground(new java.awt.Color(255, 255, 255));
        Signup.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Signup.setForeground(new java.awt.Color(123, 92, 170));
        Signup.setToolTipText("");
        Signup.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Signup.setBorderPainted(false);
        Signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignupMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignupMouseEntered(evt);
            }
        });
        Signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupActionPerformed(evt);
            }
        });
        getContentPane().add(Signup);
        Signup.setBounds(50, 460, 280, 70);
        Signup.setOpaque(false);
        Signup.setContentAreaFilled(false);
        Signup.setBorderPainted(false);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/New 2 Start page.jpg"))); // NOI18N
        background.setMaximumSize(new java.awt.Dimension(375, 830));
        background.setMinimumSize(new java.awt.Dimension(375, 830));
        getContentPane().add(background);
        background.setBounds(0, 0, 375, 812);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupActionPerformed
        // TODO add your handling code here:

        new c2_Signup().setVisible(true);
        
        this.dispose();

    }//GEN-LAST:event_SignupActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        new c1_Login().setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_LoginActionPerformed

    private void LoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseEntered
        // TODO add your handling code here:
        loginclicked.setVisible(true);
    }//GEN-LAST:event_LoginMouseEntered

    private void LoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseExited
        // TODO add your handling code here:
        loginclicked.setVisible(false);
    }//GEN-LAST:event_LoginMouseExited

    private void SignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupMouseEntered
        // TODO add your handling code here:
        signupclicked.setVisible(true);
    }//GEN-LAST:event_SignupMouseEntered

    private void SignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupMouseExited
        // TODO add your handling code here:
        signupclicked.setVisible(false);
    }//GEN-LAST:event_SignupMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(b_Startpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(b_Startpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(b_Startpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(b_Startpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new b_Startpage().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Login;
    public static javax.swing.JButton Signup;
    private javax.swing.JLabel background;
    private javax.swing.JLabel copyright;
    public static javax.swing.JLabel loginclicked;
    public static javax.swing.JLabel signupclicked;
    // End of variables declaration//GEN-END:variables
}
