/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg1bookcloud;

import javax.swing.JOptionPane;
import static pkg1bookcloud.d_Homepage.*;

/**
 *
 * @author nooralsharif
 */
public class c1_Login extends javax.swing.JFrame {

    /**
     * Creates new form c_Login
     */
    public c1_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        darkback = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        darklogin = new javax.swing.JLabel();
        error1 = new javax.swing.JLabel();
        error = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        forgotpassword = new javax.swing.JButton();
        next = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 375, 812));
        setMinimumSize(new java.awt.Dimension(375, 830));
        setSize(new java.awt.Dimension(375, 812));
        getContentPane().setLayout(null);

        darkback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/book group/New 3 Login – 3.png"))); // NOI18N
        getContentPane().add(darkback);
        darkback.setBounds(90, 680, 210, 70);
        darkback.setVisible(false);

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        back.setForeground(new java.awt.Color(123, 92, 170));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/book group/New 3 Login – 4.png"))); // NOI18N
        back.setToolTipText("");
        back.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        back.setBorderPainted(false);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(90, 680, 210, 70);
        back.setOpaque(false);
        back.setContentAreaFilled(false);
        back.setBorderPainted(false);

        darklogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/New 3 Login – 2.png"))); // NOI18N
        getContentPane().add(darklogin);
        darklogin.setBounds(89, 606, 210, 70);
        darklogin.setVisible(false);

        error1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        error1.setForeground(new java.awt.Color(255, 51, 51));
        error1.setText("* password is incorrect");
        getContentPane().add(error1);
        error1.setBounds(43, 423, 210, 20);
        error.setVisible(false);
        error1.setVisible(false);

        error.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        error.setForeground(new java.awt.Color(255, 51, 51));
        error.setText("* username is incorrect");
        getContentPane().add(error);
        error.setBounds(43, 342, 210, 20);
        error.setVisible(false);

        Username.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        Username.setForeground(new java.awt.Color(204, 204, 204));
        Username.setText("Username");
        Username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsernameMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UsernameMouseExited(evt);
            }
        });
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        getContentPane().add(Username);
        Username.setBounds(40, 340, 300, 70);

        password.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        password.setForeground(new java.awt.Color(204, 204, 204));
        password.setText("password");
        password.setPreferredSize(new java.awt.Dimension(69, 26));
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passwordMouseExited(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(40, 420, 300, 70);

        forgotpassword.setBackground(new java.awt.Color(255, 255, 255));
        forgotpassword.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        forgotpassword.setForeground(new java.awt.Color(123, 92, 170));
        forgotpassword.setToolTipText("");
        forgotpassword.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        forgotpassword.setBorderPainted(false);
        forgotpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(forgotpassword);
        forgotpassword.setBounds(180, 500, 150, 30);
        forgotpassword.setOpaque(false);
        forgotpassword.setContentAreaFilled(false);
        forgotpassword.setBorderPainted(false);

        next.setBackground(new java.awt.Color(255, 255, 255));
        next.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        next.setForeground(new java.awt.Color(123, 92, 170));
        next.setToolTipText("");
        next.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        next.setBorderPainted(false);
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextMouseEntered(evt);
            }
        });
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next);
        next.setBounds(90, 610, 210, 60);
        next.setOpaque(false);
        next.setContentAreaFilled(false);
        next.setBorderPainted(false);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/New 3 Login – 1.jpg"))); // NOI18N
        background.setMaximumSize(new java.awt.Dimension(375, 830));
        background.setMinimumSize(new java.awt.Dimension(375, 830));
        getContentPane().add(background);
        background.setBounds(0, 0, 375, 812);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        new d_Homepage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nextActionPerformed

    private void forgotpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotpasswordActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(null, "Please check your email to renew your password.", "Forgot Password", JOptionPane.PLAIN_MESSAGE);
        
        //JOptionPane.showMessageDialog(null, "Wrong password, please enter the correct password", "Error", JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_forgotpasswordActionPerformed

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_UsernameActionPerformed

    private void UsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameMouseClicked
        // TODO add your handling code here:
        Username.setText("");
    }//GEN-LAST:event_UsernameMouseClicked

    private void UsernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameMouseExited
        // TODO add your handling code here:
        String text = Username.getText();
        
        if(text.length()<= 5){
           //Username.setText(text);
           error.setVisible(true);
        }
        else{
            error.setVisible(false);
        }
    }//GEN-LAST:event_UsernameMouseExited

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
        // TODO add your handling code here:
        password.setText("");
    }//GEN-LAST:event_passwordMouseClicked

    private void passwordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseExited
        // TODO add your handling code here:
        char[] text = password.getPassword();
        
        if(text.length <= 7){
           //Username.setText(text);
           error1.setVisible(true);
        }
        else{
            error1.setVisible(false);
        }
    }//GEN-LAST:event_passwordMouseExited

    private void nextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseEntered
        // TODO add your handling code here:
        darklogin.setVisible(true);
    }//GEN-LAST:event_nextMouseEntered

    private void nextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseExited
        // TODO add your handling code here:
        darklogin.setVisible(false);
    }//GEN-LAST:event_nextMouseExited

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        // TODO add your handling code here:
        darkback.setVisible(false);
     
    }//GEN-LAST:event_backMouseExited

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        // TODO add your handling code here:
        darkback.setVisible(true);
    }//GEN-LAST:event_backMouseEntered

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new b_Startpage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(c1_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(c1_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(c1_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(c1_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new c1_Login().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Username;
    public static javax.swing.JButton back;
    private javax.swing.JLabel background;
    public static javax.swing.JLabel darkback;
    public static javax.swing.JLabel darklogin;
    public static javax.swing.JLabel error;
    public static javax.swing.JLabel error1;
    public static javax.swing.JButton forgotpassword;
    public static javax.swing.JButton next;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
