/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg1bookcloud;

/**
 *
 * @author nooralsharif
 */
public class f2_Library extends javax.swing.JFrame {

    /**
     * Creates new form f2_Library
     */
    public f2_Library() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grid = new javax.swing.JButton();
        order = new javax.swing.JComboBox<>();
        top = new javax.swing.JLabel();
        up = new javax.swing.JButton();
        down = new javax.swing.JButton();
        store = new javax.swing.JButton();
        home = new javax.swing.JButton();
        options = new javax.swing.JLabel();
        g18 = new javax.swing.JLabel();
        g17 = new javax.swing.JLabel();
        g16 = new javax.swing.JLabel();
        g15 = new javax.swing.JLabel();
        g14 = new javax.swing.JLabel();
        g13 = new javax.swing.JLabel();
        g12 = new javax.swing.JLabel();
        g11 = new javax.swing.JLabel();
        g10 = new javax.swing.JLabel();
        g9 = new javax.swing.JLabel();
        g8 = new javax.swing.JLabel();
        g7 = new javax.swing.JLabel();
        g6 = new javax.swing.JLabel();
        g5 = new javax.swing.JLabel();
        g4 = new javax.swing.JLabel();
        g3 = new javax.swing.JLabel();
        g2 = new javax.swing.JLabel();
        g1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(375, 830));
        setMinimumSize(new java.awt.Dimension(375, 830));
        setPreferredSize(new java.awt.Dimension(375, 830));
        getContentPane().setLayout(null);

        grid.setBorder(null);
        grid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gridActionPerformed(evt);
            }
        });
        getContentPane().add(grid);
        grid.setBounds(270, 100, 40, 40);
        grid.setOpaque(false);
        grid.setContentAreaFilled(false);
        grid.setBorderPainted(false);

        order.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Title", "Author", "Rating" }));
        getContentPane().add(order);
        order.setBounds(30, 110, 100, 27);

        top.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/New 9 Library list.png"))); // NOI18N
        top.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        top.setMaximumSize(new java.awt.Dimension(380, 140));
        top.setMinimumSize(new java.awt.Dimension(380, 140));
        top.setPreferredSize(new java.awt.Dimension(380, 140));
        getContentPane().add(top);
        top.setBounds(0, 0, 380, 143);

        up.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });
        getContentPane().add(up);
        up.setBounds(320, 150, 50, 110);
        up.setOpaque(false);
        up.setContentAreaFilled(false);
        up.setBorderPainted(false);

        down.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downActionPerformed(evt);
            }
        });
        getContentPane().add(down);
        down.setBounds(320, 640, 50, 110);
        down.setOpaque(false);
        down.setContentAreaFilled(false);
        down.setBorderPainted(false);

        store.setBorder(null);
        store.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeActionPerformed(evt);
            }
        });
        getContentPane().add(store);
        store.setBounds(270, 750, 60, 60);
        store.setOpaque(false);
        store.setContentAreaFilled(false);
        store.setBorderPainted(false);

        home.setBorder(null);
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home);
        home.setBounds(50, 750, 60, 60);
        home.setOpaque(false);
        home.setContentAreaFilled(false);
        home.setBorderPainted(false);

        options.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/New 8 Library grid – 1.png"))); // NOI18N
        options.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(options);
        options.setBounds(0, 750, 375, 60);

        g18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/Group/17.png"))); // NOI18N
        g18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(g18);
        g18.setBounds(30, 2580, 330, 135);

        g17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/Group/18.png"))); // NOI18N
        g17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(g17);
        g17.setBounds(30, 2730, 330, 135);

        g16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/Group/13.png"))); // NOI18N
        g16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        g16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                book(evt);
            }
        });
        getContentPane().add(g16);
        g16.setBounds(30, 1960, 330, 135);

        g15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/Group/14.png"))); // NOI18N
        g15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(g15);
        g15.setBounds(30, 2110, 330, 135);

        g14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/Group/15.png"))); // NOI18N
        g14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(g14);
        g14.setBounds(30, 2260, 330, 135);

        g13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/Group/16.png"))); // NOI18N
        g13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(g13);
        g13.setBounds(30, 2410, 330, 135);

        g12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/Group/9.png"))); // NOI18N
        g12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(g12);
        g12.setBounds(30, 1350, 330, 135);

        g11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/Group/10.png"))); // NOI18N
        g11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(g11);
        g11.setBounds(30, 1500, 330, 135);

        g10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/Group/11.png"))); // NOI18N
        g10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(g10);
        g10.setBounds(30, 1650, 330, 135);

        g9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/Group/12.png"))); // NOI18N
        g9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(g9);
        g9.setBounds(30, 1800, 330, 135);

        g8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/Group/5.png"))); // NOI18N
        g8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(g8);
        g8.setBounds(30, 740, 330, 135);

        g7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/Group/6.png"))); // NOI18N
        g7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(g7);
        g7.setBounds(30, 890, 330, 135);

        g6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/Group/7.png"))); // NOI18N
        g6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(g6);
        g6.setBounds(30, 1040, 330, 135);

        g5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/Group/8.png"))); // NOI18N
        g5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(g5);
        g5.setBounds(30, 1190, 330, 135);

        g4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/Group/4.png"))); // NOI18N
        g4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        g4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                g1MouseClicked(evt);
            }
        });
        getContentPane().add(g4);
        g4.setBounds(30, 595, 330, 135);

        g3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/Group/3.png"))); // NOI18N
        g3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        g3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                g1MouseClicked(evt);
            }
        });
        getContentPane().add(g3);
        g3.setBounds(30, 446, 330, 135);

        g2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/Group/2.png"))); // NOI18N
        g2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        g2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                g1MouseClicked1(evt);
            }
        });
        getContentPane().add(g2);
        g2.setBounds(30, 300, 330, 135);

        g1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/Group/1.png"))); // NOI18N
        g1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        g1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                g1MouseClicked1(evt);
            }
        });
        getContentPane().add(g1);
        g1.setBounds(30, 150, 330, 135);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/New 8 Library grid – 1.png"))); // NOI18N
        background.setMaximumSize(new java.awt.Dimension(375, 830));
        background.setMinimumSize(new java.awt.Dimension(375, 830));
        background.setPreferredSize(new java.awt.Dimension(375, 830));
        getContentPane().add(background);
        background.setBounds(0, 0, 375, 810);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
        // TODO add your handling code here:

        //if ( ((book13.getY()- 20) >= 594)  && ((book14.getY()- 20) >= 594)  && ((book15.getY()- 20) >= 594)){
            if ( /*((g16.getY()- 20) >= 588)  && ((g17.getY()- 20) >= 588)  &&*/ ((g17.getY()- 50) >= 580)){

                g1.setLocation(g1.getX(), g1.getY() -50);
                g2.setLocation(g2.getX(), g2.getY() -50);
                g3.setLocation(g3.getX(), g3.getY() -50);
                g4.setLocation(g4.getX(), g4.getY() -50);
                g5.setLocation(g5.getX(), g5.getY() -50);
                g6.setLocation(g6.getX(), g6.getY() -50);
                g7.setLocation(g7.getX(), g7.getY() -50);
                g8.setLocation(g8.getX(), g8.getY() -50);
                g9.setLocation(g9.getX(), g9.getY() -50);
                g10.setLocation(g10.getX(), g10.getY() -50);
                g11.setLocation(g11.getX(), g11.getY() -50);
                g12.setLocation(g12.getX(), g12.getY() -50);
                g13.setLocation(g13.getX(), g13.getY() -50);
                g14.setLocation(g14.getX(), g14.getY() -50);
                g15.setLocation(g15.getX(), g15.getY() -50);

                g16.setLocation(g16.getX(), g16.getY() -50);
                g17.setLocation(g17.getX(), g17.getY() -50);
                g18.setLocation(g18.getX(), g18.getY() -50);
            }

    }//GEN-LAST:event_upActionPerformed

    private void downActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downActionPerformed
        // TODO add your handling code here:

        if ( ((g1.getY()+ 50) <= 153)  /*&& ((g2.getY()+ 20) <= 153)  && ((g3.getY()+ 20) <= 153)*/){

            g1.setLocation(g1.getX(), g1.getY() +50);
            g2.setLocation(g2.getX(), g2.getY() +50);
            g3.setLocation(g3.getX(), g3.getY() +50);
            g4.setLocation(g4.getX(), g4.getY() +50);
            g5.setLocation(g5.getX(), g5.getY() +50);
            g6.setLocation(g6.getX(), g6.getY() +50);
            g7.setLocation(g7.getX(), g7.getY() +50);
            g8.setLocation(g8.getX(), g8.getY() +50);
            g9.setLocation(g9.getX(), g9.getY() +50);
            g10.setLocation(g10.getX(), g10.getY() +50);
            g11.setLocation(g11.getX(), g11.getY() +50);
            g12.setLocation(g12.getX(), g12.getY() +50);
            g13.setLocation(g13.getX(), g13.getY() +50);
            g14.setLocation(g14.getX(), g14.getY() +50);
            g15.setLocation(g15.getX(), g15.getY() +50);

            g16.setLocation(g16.getX(), g16.getY() +50);
            g17.setLocation(g17.getX(), g17.getY() +50);
            g18.setLocation(g18.getX(), g18.getY() +50);
        }

    }//GEN-LAST:event_downActionPerformed

    private void gridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gridActionPerformed
        // TODO add your handling code here:
        new f1_Library().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gridActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        new d_Homepage().setVisible(true);
        this.dispose();    
    }//GEN-LAST:event_homeActionPerformed

    private void book(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book
        // TODO add your handling code here:
        new g_Book().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_book

    private void g1MouseClicked1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g1MouseClicked1
        // TODO add your handling code here:new g_Book().setVisible(true);
        new g_Book().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_g1MouseClicked1

    private void g1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g1MouseClicked
        // TODO add your handling code here:
        new g_Book().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_g1MouseClicked

    private void storeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeActionPerformed
        // TODO add your handling code here:
        new h_store().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_storeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f2_Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f2_Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f2_Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f2_Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f2_Library().setVisible(true);
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel background;
    public static javax.swing.JButton down;
    public static javax.swing.JLabel g1;
    public static javax.swing.JLabel g10;
    public static javax.swing.JLabel g11;
    public static javax.swing.JLabel g12;
    public static javax.swing.JLabel g13;
    public static javax.swing.JLabel g14;
    public static javax.swing.JLabel g15;
    public static javax.swing.JLabel g16;
    public static javax.swing.JLabel g17;
    public static javax.swing.JLabel g18;
    public static javax.swing.JLabel g2;
    public static javax.swing.JLabel g3;
    public static javax.swing.JLabel g4;
    public static javax.swing.JLabel g5;
    public static javax.swing.JLabel g6;
    public static javax.swing.JLabel g7;
    public static javax.swing.JLabel g8;
    public static javax.swing.JLabel g9;
    public static javax.swing.JButton grid;
    public static javax.swing.JButton home;
    public static javax.swing.JLabel options;
    private javax.swing.JComboBox<String> order;
    public static javax.swing.JButton store;
    public static javax.swing.JLabel top;
    public static javax.swing.JButton up;
    // End of variables declaration//GEN-END:variables
}
