/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg1bookcloud;

/**
 *
 * @author nooralsharif
 */
public class g_Book extends javax.swing.JFrame {

    /**
     * Creates new form g_Book
     */
    public g_Book() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        goup = new javax.swing.JButton();
        store = new javax.swing.JButton();
        library = new javax.swing.JButton();
        home = new javax.swing.JButton();
        closerate = new javax.swing.JButton();
        rate = new javax.swing.JButton();
        ch6 = new javax.swing.JButton();
        ch5 = new javax.swing.JButton();
        ch3 = new javax.swing.JButton();
        closechapter = new javax.swing.JButton();
        chapter = new javax.swing.JButton();
        chapters = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        comment = new javax.swing.JTextField();
        rating = new javax.swing.JLabel();
        godown = new javax.swing.JButton();
        labels = new javax.swing.JLabel();
        click = new javax.swing.JButton();
        closeclick = new javax.swing.JButton();
        book = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(375, 830));
        getContentPane().setLayout(null);

        goup.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        goup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goupActionPerformed(evt);
            }
        });
        getContentPane().add(goup);
        goup.setBounds(0, 0, 380, 170);
        goup.setVisible(true);
        goup.setOpaque(false);
        goup.setContentAreaFilled(false);
        goup.setBorderPainted(false);

        store.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        store.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeActionPerformed(evt);
            }
        });
        getContentPane().add(store);
        store.setBounds(270, 750, 60, 60);
        store.setOpaque(false);
        store.setContentAreaFilled(false);
        store.setBorderPainted(false);

        library.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        library.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libraryActionPerformed(evt);
            }
        });
        getContentPane().add(library);
        library.setBounds(160, 760, 50, 50);
        library.setOpaque(false);
        library.setContentAreaFilled(false);
        library.setBorderPainted(false);
        library.setVisible(false);

        home.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home);
        home.setBounds(50, 760, 50, 50);
        home.setOpaque(false);
        home.setContentAreaFilled(false);
        home.setBorderPainted(false);
        home.setVisible(false);

        closerate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        closerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closerateActionPerformed(evt);
            }
        });
        getContentPane().add(closerate);
        closerate.setBounds(50, 20, 70, 60);
        closerate.setOpaque(false);
        closerate.setContentAreaFilled(false);
        closerate.setBorderPainted(false);
        closerate.setVisible(false);

        rate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        rate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateActionPerformed(evt);
            }
        });
        getContentPane().add(rate);
        rate.setBounds(50, 20, 70, 60);
        rate.setOpaque(false);
        rate.setContentAreaFilled(false);
        rate.setBorderPainted(false);
        rate.setVisible(false);

        ch6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(ch6);
        ch6.setBounds(60, 230, 260, 40);
        ch6.setVisible(false);
        ch6.setOpaque(false);
        ch6.setContentAreaFilled(false);
        ch6.setBorderPainted(false);

        ch5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(ch5);
        ch5.setBounds(60, 180, 260, 40);
        ch5.setVisible(false);
        ch5.setOpaque(false);
        ch5.setContentAreaFilled(false);
        ch5.setBorderPainted(false);

        ch3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(ch3);
        ch3.setBounds(60, 80, 260, 40);
        ch3.setVisible(false);
        ch3.setOpaque(false);
        ch3.setContentAreaFilled(false);
        ch3.setBorderPainted(false);

        closechapter.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        closechapter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closechapterActionPerformed(evt);
            }
        });
        getContentPane().add(closechapter);
        closechapter.setBounds(130, 20, 120, 50);
        closechapter.setOpaque(false);
        closechapter.setContentAreaFilled(false);
        closechapter.setBorderPainted(false);
        closechapter.setVisible(false);

        chapter.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        chapter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chapterActionPerformed(evt);
            }
        });
        getContentPane().add(chapter);
        chapter.setBounds(130, 20, 120, 50);
        chapter.setOpaque(false);
        chapter.setContentAreaFilled(false);
        chapter.setBorderPainted(false);
        chapter.setVisible(false);

        chapters.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/New 12 Book chapters – 1.png"))); // NOI18N
        chapters.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(chapters);
        chapters.setBounds(0, 0, 380, 350);
        chapters.setVisible(false);

        submit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(submit);
        submit.setBounds(127, 409, 120, 50);
        submit.setOpaque(false);
        submit.setContentAreaFilled(false);
        submit.setBorderPainted(false);
        submit.setVisible(false);

        comment.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        comment.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(comment);
        comment.setBounds(30, 280, 320, 110);
        comment.setVisible(false);

        rating.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/New 13 Book rating – 1.png"))); // NOI18N
        rating.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(rating);
        rating.setBounds(0, 0, 380, 510);
        rating.setVisible(false);

        godown.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        godown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                godownActionPerformed(evt);
            }
        });
        getContentPane().add(godown);
        godown.setBounds(0, 640, 380, 170);
        godown.setVisible(true);
        godown.setOpaque(false);
        godown.setContentAreaFilled(false);
        godown.setBorderPainted(false);

        labels.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/New 11 Book clicked – 1.png"))); // NOI18N
        labels.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labels.setSize(new java.awt.Dimension(375, 812));
        getContentPane().add(labels);
        labels.setBounds(0, 0, 375, 812);
        labels.setVisible(false);

        click.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        click.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickActionPerformed(evt);
            }
        });
        getContentPane().add(click);
        click.setBounds(0, 0, 370, 810);
        click.setOpaque(false);
        click.setContentAreaFilled(false);
        click.setBorderPainted(false);
        click.setVisible(true);

        closeclick.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        closeclick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeclickActionPerformed(evt);
            }
        });
        getContentPane().add(closeclick);
        closeclick.setBounds(0, 0, 380, 810);
        closeclick.setOpaque(false);
        closeclick.setContentAreaFilled(false);
        closeclick.setBorderPainted(false);
        closeclick.setVisible(false);

        book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/New 10 Book.png"))); // NOI18N
        book.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        book.setMaximumSize(new java.awt.Dimension(375, 812));
        book.setMinimumSize(new java.awt.Dimension(375, 812));
        book.setPreferredSize(new java.awt.Dimension(375, 812));
        getContentPane().add(book);
        book.setBounds(0, 0, 375, 1980);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickActionPerformed
        // TODO add your handling code here:
        labels.setVisible(true);
        chapter.setVisible(true);
        rate.setVisible(true);
        
        home.setVisible(true);
        library.setVisible(true);
        store.setVisible(true);

        click.setVisible(false);
        closeclick.setVisible(true);
        
        godown.setVisible(false);
        goup.setVisible(false);
    }//GEN-LAST:event_clickActionPerformed

    private void godownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_godownActionPerformed
        // TODO add your handling code here:
        if(book.getY() -50 >=-1180){
            book.setLocation(book.getX(), book.getY()-50);
        }
        
    }//GEN-LAST:event_godownActionPerformed

    private void libraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libraryActionPerformed
        // TODO add your handling code here:
        new f1_Library().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_libraryActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        new d_Homepage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void rateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateActionPerformed
        // TODO add your handling code here:
        labels.setVisible(true);
        
        chapter.setVisible(false);
        
        rate.setVisible(false);
        rating.setVisible(true);
        comment.setVisible(true);
        submit.setVisible(true);
        closerate.setVisible(true);
        
        click.setVisible(false);
        closeclick.setVisible(false);
        
    }//GEN-LAST:event_rateActionPerformed

    private void chapterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chapterActionPerformed
        // TODO add your handling code here:
        labels.setVisible(true);
        
        rate.setVisible(false);
        
        chapter.setVisible(false);
        chapters.setVisible(true);
        ch3.setVisible(true);
        ch5.setVisible(true);
        ch6.setVisible(true);
        closechapter.setVisible(true);
        
        click.setVisible(false);
        closeclick.setVisible(false);
    }//GEN-LAST:event_chapterActionPerformed

    private void closerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closerateActionPerformed
        // TODO add your handling code here:
        labels.setVisible(true);
        
        chapter.setVisible(true);
        
        rate.setVisible(true);
        rating.setVisible(false);
        comment.setVisible(false);
        submit.setVisible(false);
        closerate.setVisible(false);
        
        click.setVisible(false);
        closeclick.setVisible(true);
    }//GEN-LAST:event_closerateActionPerformed

    private void closechapterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closechapterActionPerformed
        // TODO add your handling code here:
        labels.setVisible(true);
        
        rate.setVisible(true);
        
        chapter.setVisible(true);
        chapters.setVisible(false);
        ch3.setVisible(false);
        ch5.setVisible(false);
        ch6.setVisible(false);
        closechapter.setVisible(false);
        
        click.setVisible(false);
        closeclick.setVisible(true);
    }//GEN-LAST:event_closechapterActionPerformed

    private void closeclickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeclickActionPerformed
        // TODO add your handling code here:
        labels.setVisible(false);
        chapter.setVisible(false);
        rate.setVisible(false);
        
        home.setVisible(false);
        library.setVisible(false);
        store.setVisible(false);

        click.setVisible(true);
        closeclick.setVisible(false);
        
        godown.setVisible(true);
        goup.setVisible(true);
    }//GEN-LAST:event_closeclickActionPerformed

    private void goupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goupActionPerformed
        // TODO add your handling code here:
        if(book.getY() +50 <= 0){
            book.setLocation(book.getX(), book.getY()+50);
        }
    }//GEN-LAST:event_goupActionPerformed

    private void storeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeActionPerformed
        // TODO add your handling code here:
        new h_store().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_storeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(g_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(g_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(g_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(g_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new g_Book().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel book;
    public static javax.swing.JButton ch3;
    public static javax.swing.JButton ch5;
    public static javax.swing.JButton ch6;
    public static javax.swing.JButton chapter;
    public static javax.swing.JLabel chapters;
    public static javax.swing.JButton click;
    public static javax.swing.JButton closechapter;
    public static javax.swing.JButton closeclick;
    public static javax.swing.JButton closerate;
    public static javax.swing.JTextField comment;
    public static javax.swing.JButton godown;
    public static javax.swing.JButton goup;
    public static javax.swing.JButton home;
    public static javax.swing.JLabel labels;
    public static javax.swing.JButton library;
    public static javax.swing.JButton rate;
    public static javax.swing.JLabel rating;
    public static javax.swing.JButton store;
    public static javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
