/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg1bookcloud;

/**
 *
 * @author nooralsharif
 */
public class i_more extends javax.swing.JFrame {

    /**
     * Creates new form i_more
     */
    public i_more() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home = new javax.swing.JButton();
        library = new javax.swing.JButton();
        bottom = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        top = new javax.swing.JLabel();
        up = new javax.swing.JButton();
        down = new javax.swing.JButton();
        buy = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(375, 830));
        setMinimumSize(new java.awt.Dimension(375, 830));
        setPreferredSize(new java.awt.Dimension(375, 830));
        getContentPane().setLayout(null);

        home.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home);
        home.setBounds(50, 760, 50, 50);
        home.setOpaque(false);
        home.setContentAreaFilled(false);
        home.setBorderPainted(false);
        home.setVisible(true);

        library.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        library.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libraryActionPerformed(evt);
            }
        });
        getContentPane().add(library);
        library.setBounds(160, 760, 50, 50);
        library.setOpaque(false);
        library.setContentAreaFilled(false);
        library.setBorderPainted(false);
        library.setVisible(true);

        bottom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/New 16 More on book – 2.png"))); // NOI18N
        bottom.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bottom.setMaximumSize(new java.awt.Dimension(375, 830));
        bottom.setMinimumSize(new java.awt.Dimension(375, 830));
        bottom.setPreferredSize(new java.awt.Dimension(375, 830));
        getContentPane().add(bottom);
        bottom.setBounds(0, 752, 375, 56);

        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(20, 160, 60, 20);
        back.setOpaque(false);
        back.setContentAreaFilled(false);
        back.setBorderPainted(false);
        back.setVisible(true);

        top.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/New 16 More on book – 2.png"))); // NOI18N
        top.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        top.setMaximumSize(new java.awt.Dimension(375, 830));
        top.setMinimumSize(new java.awt.Dimension(375, 830));
        top.setPreferredSize(new java.awt.Dimension(375, 830));
        getContentPane().add(top);
        top.setBounds(0, 0, 375, 183);

        up.setBorder(null);
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });
        getContentPane().add(up);
        up.setBounds(330, 620, 50, 160);
        up.setOpaque(false);
        up.setContentAreaFilled(false);
        up.setBorderPainted(false);
        up.setVisible(true);

        down.setBorder(null);
        down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downActionPerformed(evt);
            }
        });
        getContentPane().add(down);
        down.setBounds(330, 210, 50, 160);
        down.setOpaque(false);
        down.setContentAreaFilled(false);
        down.setBorderPainted(false);
        down.setVisible(true);

        buy.setBorder(null);
        buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyActionPerformed(evt);
            }
        });
        getContentPane().add(buy);
        buy.setBounds(80, 1090, 200, 80);
        buy.setOpaque(false);
        buy.setContentAreaFilled(false);
        buy.setBorderPainted(false);
        buy.setVisible(true);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg1bookcloud/Book Cloud jpeg/New 16 More on book – 1.png"))); // NOI18N
        background.setMaximumSize(new java.awt.Dimension(375, 830));
        background.setMinimumSize(new java.awt.Dimension(375, 830));
        background.setPreferredSize(new java.awt.Dimension(375, 830));
        getContentPane().add(background);
        background.setBounds(0, 0, 375, 1259);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        new d_Homepage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void libraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libraryActionPerformed
        // TODO add your handling code here:
        new f1_Library().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_libraryActionPerformed

    private void downActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downActionPerformed
        // TODO add your handling code here:
        if ((background.getY() + 50) <= 0) {

            background.setLocation(background.getX(), background.getY() + 50);
            buy.setLocation(buy.getX(), buy.getY() + 50);

        }
    }//GEN-LAST:event_downActionPerformed

    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
        // TODO add your handling code here:
        if ((background.getY() - 50) >=-450) {

            background.setLocation(background.getX(), background.getY() - 50);
            buy.setLocation(buy.getX(), buy.getY() - 50);
        }
        
    }//GEN-LAST:event_upActionPerformed

    private void buyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyActionPerformed
        // TODO add your handling code here:
        new j_buy().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buyActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new h_store().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(i_more.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(i_more.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(i_more.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(i_more.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new i_more().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    public static javax.swing.JLabel background;
    public static javax.swing.JLabel bottom;
    public static javax.swing.JButton buy;
    public static javax.swing.JButton down;
    public static javax.swing.JButton home;
    public static javax.swing.JButton library;
    public static javax.swing.JLabel top;
    public static javax.swing.JButton up;
    // End of variables declaration//GEN-END:variables
}
